"use strict";
exports.__esModule = true;
var Keyword;
(function (Keyword) {
    Keyword["Class"] = "class";
    Keyword["Method"] = "method";
    Keyword["Function"] = "function";
    Keyword["Constructor"] = "constructor";
    Keyword["Int"] = "int";
    Keyword["Boolean"] = "boolean";
    Keyword["Char"] = "char";
    Keyword["Void"] = "void";
    Keyword["Var"] = "var";
    Keyword["Static"] = "static";
    Keyword["Field"] = "field";
    Keyword["Let"] = "let";
    Keyword["Do"] = "do";
    Keyword["If"] = "if";
    Keyword["Else"] = "else";
    Keyword["While"] = "while";
    Keyword["Return"] = "return";
    Keyword["True"] = "true";
    Keyword["False"] = "false";
    Keyword["Null"] = "null";
    Keyword["This"] = "this";
})(Keyword || (Keyword = {}));
exports["default"] = Keyword;
