"use strict";
exports.__esModule = true;
var Symbol;
(function (Symbol) {
    Symbol["CurlyRight"] = "{";
    Symbol["CurlyLeft"] = "}";
    Symbol["ParenRight"] = "(";
    Symbol["ParenLeft"] = ")";
    Symbol["BracketRight"] = "[";
    Symbol["BracketLeft"] = "]";
    Symbol["Period"] = ".";
    Symbol["Comma"] = ",";
    Symbol["Semi"] = ";";
    Symbol["Plus"] = "+";
    Symbol["Minus"] = "-";
    Symbol["Times"] = "*";
    Symbol["SlashRight"] = "/";
    Symbol["Ampersand"] = "&amp;";
    Symbol["Pipe"] = "|";
    Symbol["LessThan"] = "&lt;";
    Symbol["GreaterThan"] = "&gt;";
    Symbol["Equals"] = "=";
    Symbol["Not"] = "~";
})(Symbol || (Symbol = {}));
exports["default"] = Symbol;
